{
    "bf16": {
        "enabled": true 
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 0.00006,
            "weight_decay": "auto",
            "torch_adam": true,
            "adam_w_mode": true
        }
    },
        "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_min_lr": 0.00001,
            "warmup_max_lr": 0.00006,
            "warmup_num_steps": 500,
            "total_num_steps": "auto"
        }
    },
    "zero_optimization": {
        "stage": 2,
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 5e8,
        "contiguous_gradients": true
    },
    "gradient_accumulation_steps": 1,
    "train_micro_batch_size_per_gpu": 1,
    "steps_per_print": 1,
    "train_batch_size": "auto",
    "gradient_clipping": 1.0,
    "wall_clock_breakdown": false
}