compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: /capstor/scratch/cscs/sstapf/mem_wm/finetune/configs/zero2.yaml
  deepspeed_multinode_launcher: standard
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false


#compute_environment: LOCAL_MACHINE
#debug: false
#distributed_type: MULTI_GPU
#downcast_bf16: 'no'
#gpu_ids: all
#machine_rank: 0
#main_training_function: main
#mixed_precision: 'bf16'
#num_machines: 1
#num_processes: 8
#rdzv_backend: static
#same_network: true
#tpu_env: []
#tpu_use_cluster: false
#tpu_use_sudo: false
#use_cpu: false
#
#compute_environment: LOCAL_MACHINE
##gpu_ids: "0,1,2,3,4,5,6,7"
##num_processes: 8  # should be the same as the number of GPUs
#gpu_ids: "0,1,2,3"
#num_processes: 4  # should be the same as the number of GPUs
#
#debug: false
#deepspeed_config:
#  deepspeed_config_file: configs/zero2.yaml  # e.g. configs/zero2.yaml, need use absolute path
#  zero3_init_flag: false
#distributed_type: DEEPSPEED
#downcast_bf16: 'no'
#enable_cpu_affinity: false
#machine_rank: 0
#main_training_function: main
#num_machines: 1
#rdzv_backend: static
#same_network: true
#tpu_env: []
#tpu_use_cluster: false
#tpu_use_sudo: false
#use_cpu: false