compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: /capstor/scratch/cscs/sstapf/mem_wm/finetune/configs/zero2.yaml
  deepspeed_multinode_launcher: standard
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
#compute_environment: LOCAL_MACHINE
#debug: false
#deepspeed_config:
#  deepspeed_config_file: configs/zero2.yaml 
#  deepspeed_multinode_launcher: standard
#distributed_type: DEEPSPEED
#downcast_bf16: 'no'
#machine_rank: 0
#main_training_function: main
#num_machines: 1
#num_processes: 8
#rdzv_backend: static
#same_network: true
#tpu_env: []
#tpu_use_cluster: false
#tpu_use_sudo: false
#use_cpu: false

#compute_environment: local_machine
#debug: false
#deepspeed_config:
#  deepspeed_config_file: configs/zero2.yaml
#  deepspeed_multinode_launcher: standard
#distributed_type: deepspeed
#downcast_bf16: 'no'
#machine_rank: 0
#main_training_function: main
#num_machines: 1
#num_processes: 8
#rdzv_backend: static
#same_network: true
#tpu_env: []
#tpu_use_cluster: false
#tpu_use_sudo: false
#use_cpu: false


#compute_environment: local_machine
#debug: false
# specify distributed_type as `multi_gpu` for ddp

#distributed_type: "MULTI_GPU"
#num_processes: 4

#mixed_precision: fp16 #bf16 #fp16 #'bf16'
#downcast_bf16: 'no'
#gpu_ids: [0,] #all
#machine_rank: 0
#main_training_function: main
#num_machines: 1
#num_processes: 1
#rdzv_backend: static
#same_network: true
#tpu_env: []
#tpu_use_cluster: false
#tpu_use_sudo: false
#use_cpu: false
#
#compute_environment: local_machine
##gpu_ids: "0,1,2,3,4,5,6,7"
##num_processes: 8  # should be the same as the number of gpus
#gpu_ids: "0,1,2,3"
#num_processes: 4  # should be the same as the number of gpus
#